"""十二组领域端口及共享执行控制；仅定义设计签名，不提供成功占位实现。

编号沿用用户所引用的核心功能⑤–⑨。所有方法均受 CallContext 的实际授权、
累计预算和取消状态约束。返回 Outcome 不替代 SPEC.md 中的操作级不变量。
同进程依赖注入即可，无需引入十二个服务或先安装新的数据库。
"""
from __future__ import annotations

from typing import Literal, Protocol
import contract_types as t


# G01 固定读取：批量端口避免 Top-K 之后仍逐项扫描整个目录。
class ContentReader(Protocol):
    def describe(self, refs: tuple[t.FixedRef, ...], ctx: t.CallContext) -> t.Outcome[tuple[t.ContentMetadata, ...]]: ...
    def read(self, request: t.ReadRequest, ctx: t.CallContext) -> t.Outcome[t.ReadBatch]: ...
    def list_page(self, scope: t.CorpusScope, page: t.PageRequest, ctx: t.CallContext) -> t.Outcome[t.Page[t.ContentMetadata]]: ...


class ReferenceResolver(Protocol):
    def resolve(self, refs: tuple[t.LegacyRef, ...], ctx: t.CallContext) -> t.Outcome[tuple[t.EvidenceLink, ...]]: ...


# G02 分级规则归 ContentCommands，原子写入归 RevisionStore；两个抽象不互相导入实现。
class ContentCommands(Protocol):
    def validate(self, batch: t.ChangeBatch, ctx: t.CallContext) -> t.Outcome[t.ValidationReceipt]: ...
    def commit(self, batch: t.ChangeBatch, ctx: t.CallContext) -> t.Outcome[t.CommitReceipt]: ...
    def restore(self, request: t.RestoreRequest, ctx: t.CallContext) -> t.Outcome[t.CommitReceipt]: ...


class RevisionStore(Protocol):
    def apply(self, batch: t.ChangeBatch, validated: t.ValidationReceipt, ctx: t.CallContext) -> t.Outcome[t.CommitReceipt]: ...
    def history(self, owner: t.OwnerId, page: t.PageRequest, ctx: t.CallContext) -> t.Outcome[t.Page[t.CommitReceipt]]: ...


# G03 多表示：缺失能力可被发现；有新语义的生成结果必须走内容提交。
class RepresentationCatalog(Protocol):
    def list(self, refs: tuple[t.FixedRef, ...], requested: t.RepresentationSpec, ctx: t.CallContext) -> t.Outcome[tuple[t.RepresentationAvailability, ...]]: ...
    def read(self, refs: tuple[t.FixedRef, ...], ctx: t.CallContext) -> t.Outcome[t.ReadBatch]: ...


class RepresentationBuilder(Protocol):
    def plan(self, refs: tuple[t.FixedRef, ...], scope: t.CorpusScope, requested: t.RepresentationSpec, strategy: t.StrategyRef, ctx: t.CallContext) -> t.Outcome[t.RepresentationPlan]: ...
    def build(self, plan: t.RepresentationPlan, ctx: t.CallContext) -> t.Outcome[t.RepresentationBuild]: ...


# G04 投影与索引：增量、全量、补偿共享计划/执行契约，水位与内容提交分别报告。
class ChangeReader(Protocol):
    def read(self, scope: t.CorpusScope, page: t.PageRequest, ctx: t.CallContext) -> t.Outcome[t.Page[t.ChangeEvent]]: ...


class IndexLifecycle(Protocol):
    def status(self, indexes: tuple[t.IndexKey, ...], scope: t.CorpusScope, ctx: t.CallContext) -> t.Outcome[tuple[t.Watermark, ...]]: ...
    def plan(self, mode: Literal["incremental", "rebuild", "repair"], index: t.IndexKey, scope: t.CorpusScope, changes: t.Page[t.ChangeEvent] | None, contents: t.Page[t.ContentMetadata] | None, ctx: t.CallContext) -> t.Outcome[t.IndexPlan]: ...
    def execute(self, plan: t.IndexPlan, ctx: t.CallContext) -> t.Outcome[t.IndexReceipt]: ...


# G05 召回：每个实现可支持一部分通道，但必须拒绝无法满足的硬约束。
class RecallProvider(Protocol):
    def capabilities(self, ctx: t.CallContext) -> t.Outcome[t.ProviderCapabilities]: ...
    def recall(self, request: t.RecallRequest, ctx: t.CallContext) -> t.Outcome[t.CandidateBatch]: ...


# G06 纯排序策略可逐个替换；外层流水线保留全部通道来源和降级信息。
class CandidateDeduplicator(Protocol):
    def deduplicate(self, batches: tuple[t.CandidateBatch, ...], ctx: t.CallContext) -> t.Outcome[t.CandidateBatch]: ...


class FusionStrategy(Protocol):
    def fuse(self, query: t.QuerySpec, batch: t.CandidateBatch, ctx: t.CallContext) -> t.Outcome[t.RankedBatch]: ...


class Reranker(Protocol):
    def rerank(self, query: t.QuerySpec, ranked: t.RankedBatch, texts: tuple[t.TextSlice, ...], ctx: t.CallContext) -> t.Outcome[t.RankedBatch]: ...


class DiversitySelector(Protocol):
    def select(self, query: t.QuerySpec, ranked: t.RankedBatch, limit: int, ctx: t.CallContext) -> t.Outcome[t.RankedBatch]: ...


class RankingPipeline(Protocol):
    def rank(self, request: t.RankingRequest, ctx: t.CallContext) -> t.Outcome[t.RankedBatch]: ...


# G07 关系导航：提出关联与正式知识写入分开，路径的固定来源可回读。
class RelationNavigator(Protocol):
    def neighbors(self, request: t.GraphRequest, ctx: t.CallContext) -> t.Outcome[t.GraphSlice]: ...
    def paths(self, request: t.GraphRequest, ctx: t.CallContext) -> t.Outcome[t.GraphSlice]: ...
    def suggest_links(self, request: t.GraphRequest, strategy: t.StrategyRef, ctx: t.CallContext) -> t.Outcome[t.GraphSlice]: ...


# G08 编排拥有查询状态；续查验证保存状态，不相信客户端重新传入的剩余额度。
class ExpansionPolicy(Protocol):
    def next_step(self, progress: t.SearchProgress, capabilities: tuple[t.ProviderCapabilities, ...], ctx: t.CallContext) -> t.Outcome[t.ExpansionStep]: ...


class SearchCoordinator(Protocol):
    def search(self, query: t.QuerySpec, context: t.ContextOptions | None, ctx: t.CallContext) -> t.Outcome[t.SearchReceipt]: ...
    def resume(self, request: t.ResumeRequest, ctx: t.CallContext) -> t.Outcome[t.SearchReceipt]: ...


# G09 组装只展开显式固定候选；发现缺口后交给 G08 决定是否再召回。
class ContextBuilder(Protocol):
    def build(self, request: t.ContextRequest, ctx: t.CallContext) -> t.Outcome[t.ContextPacket]: ...


# G10 阅读不是重新研究：拼装已有正文，有新解释时交给 G11/G02 保存。
class ReadViewService(Protocol):
    def list(self, scope: t.CorpusScope, page: t.PageRequest, ctx: t.CallContext) -> t.Outcome[t.Page[t.ContentMetadata]]: ...
    def render(self, request: t.ViewRequest, ctx: t.CallContext) -> t.Outcome[t.ReadView]: ...


# G11 整理可按策略正式修订；执行和复核状态独立，跨 owner 逐项回执。
class MaintenancePlanner(Protocol):
    def plan(self, request: t.MaintenanceRequest, ctx: t.CallContext) -> t.Outcome[t.MaintenancePlan]: ...


class MaintenanceExecutor(Protocol):
    def execute(self, plan: t.MaintenancePlan, resume: t.Cursor | None, ctx: t.CallContext) -> t.Outcome[t.MaintenanceReceipt]: ...
    def status(self, plan_id: str, ctx: t.CallContext) -> t.Outcome[t.MaintenanceReceipt]: ...


# G12 证据和授权是跨功能端口；检索分数与来源复核不得相互代替。
class EvidencePolicy(Protocol):
    def authorize(self, scope: t.CorpusScope, action: Literal["read", "query", "write", "review", "maintain"], ctx: t.CallContext) -> t.Outcome[t.AccessDecision]: ...
    def assess(self, refs: tuple[t.FixedRef, ...], purpose: Literal["exploration", "formal", "audit"], applicability: t.Applicability | None, basis: t.ReadBasis, ctx: t.CallContext) -> t.Outcome[tuple[t.EvidenceAssessment, ...]]: ...


class ReviewService(Protocol):
    def append_review(self, command: t.ReviewCommand, ctx: t.CallContext) -> t.Outcome[t.EvidenceAssessment]: ...


class ImpactAnalyzer(Protocol):
    def affected(self, refs: tuple[t.FixedRef, ...], scope: t.CorpusScope, page: t.PageRequest, ctx: t.CallContext) -> t.Outcome[t.Page[t.FixedRef]]: ...


# 横切控制不是第十三个业务模块；实现通常是进程内累计账本和取消令牌。
class ExecutionControl(Protocol):
    def reserve(self, ceiling: t.BudgetUsage, ctx: t.CallContext) -> t.Outcome[t.BudgetReservation]: ...
    def settle(self, reservation: t.BudgetReservation, actual: t.BudgetUsage, ctx: t.CallContext) -> t.Outcome[t.BudgetUsage]: ...
    def check_cancelled(self, ctx: t.CallContext) -> t.Outcome[bool]: ...
