import { compileFromFile } from "json-schema-to-typescript";
import { format } from "prettier";
import { mkdir, readFile, writeFile } from "node:fs/promises";
await mkdir("src/generated", { recursive: true });
await writeFile(
  "src/generated/contracts.ts",
  await compileFromFile("contracts/graph.schema.json"),
);
// Regenerate the offline frontend contract from the authoritative Python schema.
const memorySchema = JSON.parse(
  await readFile("../schemas/memory-v3.schema.json", "utf8"),
);
await writeFile(
  "src/generated/memory-schema.ts",
  await format(
    "// Generated by scripts/contracts.mjs; do not edit.\nexport const memorySchema = " +
      JSON.stringify(memorySchema) +
      ";\n",
    { parser: "typescript" },
  ),
);
