"""Generate TypeScript structural types from the limited memory schema (stdlib only).

Run with --check in CI to detect stale generated types. Domain rules remain in
the Python service; these declarations are intended for W10 to import directly.
"""
import argparse
import json
from pathlib import Path


SCHEMA_PATH = Path(__file__).resolve().parents[2] / "schemas" / "memory-v3.schema.json"


def render_type(schema):
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "enum" in schema:
        return " | ".join(json.dumps(v, ensure_ascii=False) for v in schema["enum"])
    if "oneOf" in schema:
        return " | ".join("(" + render_type(v) + ")" for v in schema["oneOf"])
    kind = schema.get("type")
    if isinstance(kind, list):
        return " | ".join(render_type(dict(schema, type=t)) for t in kind)
    if kind == "array":
        return "Array<" + render_type(schema["items"]) + ">"
    if kind == "object":
        required = schema.get("required", [])
        fields = [json.dumps(k) + ("" if k in required else "?") + ": " + render_type(v)
                  for k, v in schema.get("properties", {}).items()]
        extra = schema.get("additionalProperties", False)
        if isinstance(extra, dict):
            fields.append("[key: string]: " + render_type(extra))
        elif extra is True:
            fields.append("[key: string]: unknown")
        return "{ " + "; ".join(fields) + " }"
    return {"string": "string", "integer": "number", "number": "number",
            "boolean": "boolean", "null": "null"}.get(kind, "unknown")


def generate(schema):
    return "// Generated by memory/generate_types.py; do not edit. Domain validation uses backend preflight.\n" + "\n".join(
        "export type " + name + " = " + render_type(value) + ";"
        for name, value in schema["$defs"].items()) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Exit 1 if generated types differ")
    args = parser.parse_args()
    output = SCHEMA_PATH.with_suffix("").with_suffix(".d.ts")
    content = generate(json.loads(SCHEMA_PATH.read_text(encoding="utf-8")))
    if args.check:
        return 0 if output.exists() and output.read_text(encoding="utf-8") == content else 1
    output.write_text(content, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
